name = "PythonPlot"
uuid = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
version = "1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
PythonCall = "0.5"
CondaPkg = "0.2"
julia = "1.4"
LaTeXStrings = "1"
Colors = "0.9, 0.10, 0.11, 0.12, 1"
VersionParsing = "1"
